[package]
name = "rs-song-request-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.5.4"
actix-files = "0.5.0"
actix-web = "3"
derive_more = "0.99.14"
serde = "1.0.126"
